# docker/Dockerfile.worker
FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app  

# Command to run Flower
CMD ["celery", "-A", "tasks.analyzer_tasks", "flower"]