# docker/Dockerfile.api
FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt .
COPY test/requirements_test.txt /app/test/.
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get install -y curl
COPY . /app

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]