# docker/Dockerfile.worker
FROM python:3.9-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app  

CMD ["celery", "-A", "tasks.analyzer_tasks", "worker", "--loglevel=info", "--concurrency=2"]