# docker/Dockerfile.api
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .

RUN mkdir -p tests
COPY tests/requirements_test.txt tests/.

RUN pip install --no-cache-dir -r requirements.txt

RUN apt-get update && apt-get install -y curl
COPY . /app

CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]